config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions"}

  root to: 'items#index'
  resources :items do
    collection do
      get 'category'
    end
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :age
  belongs_to :skin_type
  belongs_to :personal_color
  belongs_to :face_type

  has_many :items

  validates :nickname, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, allow_blank: true
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  def new
    def new
      @user = user.where('age_id IN(?)', params[:age_id])
    super
    end
  end

  def create
    super
  end
  
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :age_id, :skin_type_id, :personal_color_id, :face_type_id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
   super
 end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @items = @user.items.includes(:user)
    @foundation = Category.find(2)
    @concealer = Category.find(3)
    @powder = Category.find(4)
    @eyebrow = Category.find(5)
    @eyeliner = Category.find(6)
    @eyeshadow = Category.find(7)
    @mascara = Category.find(8)
    @lip = Category.find(9)
    @cheek = Category.find(10) 
  end

  def edit
  end

  def update
    if @user.id == current_user.id 
      @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end 
  end

  def search
    @q = User.ransack(params[:q])
    @results = @q.result(distinct: true)
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :age_id, :skin_type_id, :personal_color_id, :face_type_id)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

<%= form_with model: @user, local: true do |f| %>
<div class="probox" >
  <div class="outoline" >
    <h2 class = "salmonpink">Edit account</h2>
    <div class="cosmeinfo">
      <h5>Nickname</h5><p>
      <div class="inputbox">
        <span class="required">*</span><%= f.text_field :nickname, id:"nickname",class:"selectb"%>
      </div>
      <h5>Age</h5><p>
      <div class="input">
        <%= f.collection_select(:age_id, Age.all, :id, :name, {}, {class:"selectbox2"}) %>
      </div>
      <h5>Skin type</h5><p>
      <div class="input">
        <%= f.collection_select(:skin_type_id, SkinType.all, :id, :name, {}, {class:"selectbox2"}) %>
      </div>
      <h5>Personal color</h5><p>
      <div class="input">
        <%= f.collection_select(:personal_color_id, PersonalColor.all, :id, :name, {}, {class:"selectbox2"}) %>
      </div>
      <h5>Face type</h5><p>
      <div class="input">
        <%= f.collection_select(:face_type_id, FaceType.all, :id, :name, {}, {class:"selectbox2"}) %>
      </div>

      <button class="button submit">account update</button>
    </div>
  </div>
</div>
<% end %>

app/views/users/search.html.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

<div class="box-a" >
  <div class="content-a" >
    <h2 class = "pink">search user</h2>
    <%= search_form_for @q, url: search_users_path do |f| %>
      <div class="search-field">
        <%= f.collection_select(:age_id_eq, Age.where.not(id: 1), :id, :name, {include_blank: "Age"}, {class:"select-box2"}) %>
      </div>
      <div class="search-field">
        <%= f.collection_select(:skin_type_id_eq, SkinType.where.not(id: 1), :id, :name, {include_blank: "Skin type"}, {class:"select-box2"}) %>
      </div>
      <div class="search-field">
        <%= f.collection_select(:personal_color_id_eq, PersonalColor.where.not(id: 1), :id, :name, {include_blank: "Personal color"}, {class:"select-box2"}) %>
      </div>
      <div class="search-field">
        <%= f.collection_select(:face_type_id_eq, FaceType.where.not(id: 1), :id, :name, {include_blank: "Face type"}, {class:"select-box2"}) %>
      </div>
        <button class="button submit">search</button>
    <% end %>
  </div>
</div>

<div class="rank">
  <% @results.each do |user| %>
    <div class="products">
    <%= link_to user_path(user.id) do %>
      <div class="product">
      <%= image_tag "usericon.png", class:"image2" %>
        <div class="brand">
        <%= user.nickname %>
        </div>
      </div>
    <% end %>
    </div> 
  <% end %>
</div>

app/views/users/show.html.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

<div class="probox2">
  <div class="blok2">
    <div class="product-info2">
      <h2 class = "salmonpink">Edit account</h2>    
      <div class="item-title">
        <h5>Nickname</h5><p>    
        <div class="user-nickname">
          <%= @user.nickname %>
        </div>
      </div>
      <div class="border3"></div>
      <div class="item-title">
        <h5>Age</h5><p>    
        <div class="user-age">
        <% if @user.age.present? %>
          <%= @user.age.name %>
        <% end %>
        </div>
      </div>
      <div class="border3"></div>
      <div class="item-title">
        <h5>Skin type</h5><p>    
        <div class="user-skin-type">
        <% if @user.skin_type.present? %>
          <%= @user.skin_type.name %>
        <% end %>
        </div>
      </div>
      <div class="border3"></div>
      <div class="item-title">
        <h5>Personal color</h5><p>    
        <div class="user-personal-color">
        <% if @user.personal_color.present? %>
          <%= @user.personal_color.name %>
        <% end %>
        </div>
      </div>
      <div class="border3"></div>
      <div class="item-title">
        <h5>Face type</h5><p>    
        <div class="user-face-type">
        <% if @user.face_type.present? %>
          <%= @user.face_type.name %>
        <% end %>
        </div>
      </div>
      <div class="border3"></div>
    </div>
    <% if current_user.id == @user.id %>
    <div class="buttons2">
      <button class="button3 submit2"><strong>
        <%= link_to "edit", edit_user_path(@user.id), method: :get, class: "click2"%>
      </strong></button>     
      <button class="button3 submit2"><strong>
        <%= link_to "logauto", destroy_user_session_path, method: :delete, class: "click2"%>
      </strong></button>
    </div>
    <% else %>
      <button class="button5"><strong>
        <%= link_to "user search", search_users_path, method: :get, class: "click2"%>
      </strong></button>     
    </div>
    <% end %>
  </div>
</div>

<div class="rank">
  <% @items.each do |item| %>
  <div class="products">
  <%= link_to item_path(item.id) do %>
    <div class="product">
      <% if item.category == @foundation %>
        <%= image_tag "foundation.png", class:"image" %>
      <% elsif item.category == @concealer %>
        <%= image_tag "concealer.png", class:"image" %>
      <% elsif item.category == @powder %>
        <%= image_tag "powder.png", class:"image" %>
      <% elsif item.category == @eyebrow %>
        <%= image_tag "eyebrow.png", class:"image" %>
      <% elsif item.category == @eyeliner %>
        <%= image_tag "eyeliner.png", class:"image" %>
      <% elsif item.category == @eyeshadow %>
        <%= image_tag "eyeshadow.png", class:"image" %>
      <% elsif item.category == @mascara %>
        <%= image_tag "mascara.png", class:"image" %>
      <% elsif item.category == @lip %>
        <%= image_tag "lip.png", class:"image" %>
      <% elsif item.category == @cheek %>
        <%= image_tag "cheek.png", class:"image" %>
      <% end %>
      <div class="brand">
        <%= item.brand %>
      </div>
      <div class="name">
        <%= item.name %>
      </div>
    </div>
  <% end %>
  </div>
  <% end %>
</div>