config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions"}

  root to: 'items#index'
  resources :items do
    collection do
      get 'category'
    end
  end

  resources :users, only: [:show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :brand, presence: true
  validates :name, presence: true
  validates :category_id, numericality: { other_than: 1 }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  def self.category
    Item.where(category_id: @category )
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :prevent_url, only: [:edit, :destroy]

  def index
    @items = current_user.items.all.order("created_at DESC")
    @foundation = Category.find(2)
    @concealer = Category.find(3)
    @powder = Category.find(4)
    @eyebrow = Category.find(5)
    @eyeliner = Category.find(6)
    @eyeshadow = Category.find(7)
    @mascara = Category.find(8)
    @lip = Category.find(9)
    @cheek = Category.find(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @foundation = Category.find(2)
    @concealer = Category.find(3)
    @powder = Category.find(4)
    @eyebrow = Category.find(5)
    @eyeliner = Category.find(6)
    @eyeshadow = Category.find(7)
    @mascara = Category.find(8)
    @lip = Category.find(9)
    @cheek = Category.find(10) 
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def category
    @items = current_user.items.where(category_id: params[:category_id]).order(created_at: :desc)  
    @foundation = Category.find(2)
    @concealer = Category.find(3)
    @powder = Category.find(4)
    @eyebrow = Category.find(5)
    @eyeliner = Category.find(6)
    @eyeshadow = Category.find(7)
    @mascara = Category.find(8)
    @lip = Category.find(9)
    @cheek = Category.find(10) 
  end

  private

  def item_params
    params.require(:item).permit(:brand, :category_id, :name, :memo).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def prevent_url
    if @item.user_id != current_user.id
      redirect_to root_path
    end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/category.html.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

  <div class="rank">
  <% @items.each do |item| %>
    <div class="products">
    <%= link_to item_path(@items.ids) do %>
      <div class="product">
        <% if item.category == @foundation %>
          <%= image_tag "foundation.png", class:"image" %>
        <% elsif item.category == @concealer %>
          <%= image_tag "concealer.png", class:"image" %>
        <% elsif item.category == @powder %>
          <%= image_tag "powder.png", class:"image" %>
        <% elsif item.category == @eyebrow %>
          <%= image_tag "eyebrow.png", class:"image" %>
        <% elsif item.category == @eyeliner %>
          <%= image_tag "eyeliner.png", class:"image" %>
        <% elsif item.category == @eyeshadow %>
          <%= image_tag "eyeshadow.png", class:"image" %>
        <% elsif item.category == @mascara %>
          <%= image_tag "mascara.png", class:"image" %>
        <% elsif item.category == @lip %>
          <%= image_tag "lip.png", class:"image" %>
        <% elsif item.category == @cheek %>
          <%= image_tag "cheek.png", class:"image" %>
        <% end %>
      <div class="brand">
        <%= item.brand %>
      </div>
      <div class="name">
        <%= item.name %>
      </div>
      </div>
    <% end %>
    </div>
  <% end %>
  </div>

app/views/items/edit.html.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

<%= render 'shared/error_messages', model: @item %>

<%= form_with model: @item, local: true do |f| %>
  <div class="box" >
    <div class="content" >
      <h2 class = "pink">Edit Cosme</h2>
      <div class="cosmeinfo">
        <h5>Brand</h5><p>
        <div class="inputbox">
          <span class="required">*</span><%= f.text_field :brand, id:"brand", placeholder:"ex.) LUNASOL" ,class:"selectb"%>
        </div>
        <h5>Category</h5><p>
        <div class="input">
          <span class="required">*</span><%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"selectbox"}) %>
        </div>
        <h5>Name</h5><p>
        <div class="inputbox">
          <span class="required">*</span><%= f.text_field :name, id:"name", placeholder:"ex.) eye coloration", class:"selectb" %>
        </div>
        <h5>Memo</h5><p>
        <div class="memo">
          <%= f.text_area :memo, id:"memo" %>
        </div>
        <button class="button submit">update</button>
      </div>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<header>
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
  <div class="search">
    <%= link_to  image_tag("searchicon.png", class:"searchicon"), search_users_path %>
  </div>
  <div class="user">
    <%= link_to  image_tag("usericon.png", class:"greeting"), user_path(id: current_user)%>
  </div>
</header>

<nav>
  <div class="dropdown">
    <a class="dropbtn">Base</a>
    <div class="dropdown_content">
      <%= link_to "Foundation", category_items_path(category_id:"2") %>
    <a div="nav_link">
      <%= link_to "Concealer", category_items_path(category_id:"3") %>
    </a>
    <a div="nav_link">
      <%= link_to "Powder", category_items_path(category_id:"4") %>
    </a>
    </div>
  </div>
  <div class="dropdown">
    <%= link_to "Eyebrow", category_items_path(category_id:"5"), class:"dropbtn" %>
  </div>
  <div class="dropdown">
    <a class="dropbtn">Eye</a>
    <div class="dropdown_content">
    <a div="nav_link">
      <%= link_to "Eyeliner", category_items_path(category_id:"6") %>
    </a>
    <a div="nav_link">
      <%= link_to "Eyeshadow", category_items_path(category_id:"7") %>
    </a>
    <a div="nav_link">
      <%= link_to "Mascara", category_items_path(category_id:"8") %>    
    </a>
    </div>
  </div>
  <div class="dropdown">
    <%= link_to "Lip", category_items_path(category_id:"9"), class:"dropbtn" %>
  </div>
  <div class="dropdown">
    <%= link_to "Cheek", category_items_path(category_id:"10"), class:"dropbtn" %>
  </div>
</nav>

<section>
  <span>
    <%= link_to "New Cosme + ",new_item_path, method: :get, class: 'btn'  %>
  </span>
  <div class="rank">
    <% @items.each do |item| %>
    <div class="products">
    <%= link_to item_path(item.id) do %>
      <div class="product">
        <% if item.category == @foundation %>
          <%= image_tag "foundation.png", class:"image" %>
        <% elsif item.category == @concealer %>
          <%= image_tag "concealer.png", class:"image" %>
        <% elsif item.category == @powder %>
          <%= image_tag "powder.png", class:"image" %>
        <% elsif item.category == @eyebrow %>
          <%= image_tag "eyebrow.png", class:"image" %>
        <% elsif item.category == @eyeliner %>
          <%= image_tag "eyeliner.png", class:"image" %>
        <% elsif item.category == @eyeshadow %>
          <%= image_tag "eyeshadow.png", class:"image" %>
        <% elsif item.category == @mascara %>
          <%= image_tag "mascara.png", class:"image" %>
        <% elsif item.category == @lip %>
          <%= image_tag "lip.png", class:"image" %>
        <% elsif item.category == @cheek %>
          <%= image_tag "cheek.png", class:"image" %>
        <% end %>
        <div class="category">
          <%= item.category.name %>
        </div>
        <div class="brand">
          <%= item.brand %>
        </div>
        <div class="name">
          <%= item.name %>
        </div>
      </div>
    <% end %>
    </div>
    <% end %>
    <h6>Copyright (c) by Katheryn & Julia Park <br>
        Released under the MIT license</h6>
  </div>
</section>

app/views/items/new.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

<%= render 'shared/error_messages', model: @item  %>

<div class="box" >
  <div class="content" >
    <h2 class = "pink">New Cosme</h2>
    <%= form_with model: @item, url: items_path, method: :post, local: true do |f| %>
    <div class="cosmeinfo">
      <h5>Brand</h5><p>
      <div class="inputbox">
        <span class="required">*</span><%= f.text_field :brand, id:"brand", placeholder:"ex.) LUNASOL" ,class:"selectb"%>
      </div>
      <h5>Category</h5><p>
      <div class="input">
        <span class="required">*</span><%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"selectbox"}) %>
      </div>
      <h5>Name</h5><p>
      <div class="inputbox">
        <span class="required">*</span><%= f.text_field :name, id:"name", placeholder:"ex.) eye coloration", class:"selectb" %>
      </div>
      <h5>Memo</h5><p>
      <div class="memo">
        <%= f.text_area :memo, id:"memo" %>
      </div>
      <button class="button submit">post</button>
      </div>
    <% end %>
  </div>
</div>

app/views/items/show.erb
<div class="rogoback">  
  <h1 class = "rogo"><%= link_to "Cosme Box", root_path, class:"rogo"%></h1>
</div>

<div class="pro">
  <div class="blok">
    <% if @item.category == @foundation %>
      <%= image_tag "foundation.png", class:"image" %>
    <% elsif @item.category == @concealer %>
      <%= image_tag "concealer.png", class:"image" %>
    <% elsif @item.category == @powder %>
      <%= image_tag "powder.png", class:"image" %>
    <% elsif @item.category == @eyebrow %>
      <%= image_tag "eyebrow.png", class:"image" %>
    <% elsif @item.category == @eyeliner %>
      <%= image_tag "eyeliner.png", class:"image" %>
    <% elsif @item.category == @eyeshadow %>
      <%= image_tag "eyeshadow.png", class:"image" %>
    <% elsif @item.category == @mascara %>
      <%= image_tag "mascara.png", class:"image" %>
    <% elsif @item.category == @lip %>
      <%= image_tag "lip.png", class:"image" %>
    <% elsif @item.category == @cheek %>
      <%= image_tag "cheek.png", class:"image" %>
    <% end %>
  <div class="product-info">    
    <div class="brand">
      <%= @item.brand %>
    </div>
    <div class="name">
      <%= @item.name %>
    </div>
    <div class="border2"></div>
    <h5>Memo</h5><p>
    <div class="memo">
      <%= @item.memo %>
    </div>
  </div>
  <% if current_user.id == @item.user_id %>
  <div class="buttons">
    <button class="button2">      
      <strong>
        <%= link_to "edit", edit_item_path(@item.id), method: :get, class: "click"%>
      </strong>
    </button>      
    <button class="button2">
      <strong>
        <%= link_to "delete", item_path(@item.id), method: :delete, class: "click"%>
      </strong>
    </button>
  </div>
  <% else %>
  <div class="buttons">
    <button class="button4">      
      <strong>
        <%= link_to "user search", search_users_path, method: :get, class: "click"%>
      </strong>
    </button>      
  </div>
  <% end %>
  </div>
</div>